//
//  Constants.swift
//  FirebaseChat
//
//  Created by Amit Chauhan on 21/04/20.
//  Copyright © 2020 Amit Chauhan. All rights reserved.
//

import Foundation
import UIKit

class Constants: NSObject {
    
    /**
     MARK: - App Constants
     */
    static let kAppDelegate    = UIApplication.shared.delegate as! AppDelegate
    static let kUserDefault    = UserDefaults.standard
    static let kScreenWidth    = UIScreen.main.bounds.width
    static let kScreenHeight   = UIScreen.main.bounds.height
    
    static let GOOGLE_API_KEY = "AIzaSyC6mxIWnQVEkBuOfrxlqE2SoqIM-n6SRSg" // current citytourdemo key "this key is generated by mobile.developer A/C for "City Tour Constanta" name"

}
