# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatDemo

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'Firebase/Messaging'
  pod 'SDWebImage'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'Alamofire', '~> 4.9.1'
  pod 'MBProgressHUD'

  target 'ChatDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
